project_id = "rsvrhwslkonyrqfvqzzv"

[functions.vapi-assistant]
verify_jwt = true

[functions.vapi-webhook]
verify_jwt = false

[functions.retell-agent]
verify_jwt = true

[functions.retell-webhook]
verify_jwt = false