project_id = "rsvrhwslkonyrqfvqzzv"

[functions.vapi-assistant]
verify_jwt = true

[functions.vapi-webhook]
verify_jwt = false

[functions.retell-agent]
verify_jwt = true

[functions.retell-webhook]
verify_jwt = false

[functions.retell-create-order]
verify_jwt = false

[functions.retell-conversation-flow]
verify_jwt = true

[functions.retell-knowledge-base]
verify_jwt = true

[functions.retell-get-flow]
verify_jwt = false

[functions.retell-pronunciation]
verify_jwt = true

[functions.elevenlabs-create-order]
verify_jwt = false
