project_id = "rsvrhwslkonyrqfvqzzv"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.retell-webhook]
verify_jwt = false

[functions.vapi-webhook]
verify_jwt = false

[functions.webhook-tool]
verify_jwt = false

[functions.elevenlabs-configure-tool]
verify_jwt = false
